image: Visual Studio 2017

build: off

test_script:
- cd "C:\Tools\vcpkg"
- git pull
- bootstrap-vcpkg.bat
- vcpkg update
- vcpkg install grpc

on_failure:
- appveyor PushArtifact C:\Tools\vcpkg\buildtrees\grpc\install-x86-windows-dbg-out.log
